### ISSUE TITLE
Allow for a wider "Miners" table

### ISSUE THREAD

**Issue by eupraxic** [sammy007/ether-proxy#1]
At times, the "ID" or "Last Share" fields are text-wrapped to fit the fixed table width of 730px.  Either increase the default table width, or allow it to be configured in config.json, or change the table formatting to avoid text-wrapping field contents.

**Comment by sammy007** [comment]
You can change

    <div class="container">

to

    <div class="container-fluid">

on your machine.

**Comment by eupraxic** [comment]
That helps, thanks!

**Comment by sammy007** [comment]
Layout extended now.
