### ISSUE TITLE
Unsolicited response received on idle HTTP channel starting with..

### ISSUE THREAD

**Issue by jeeweevee** [sammy007/ether-proxy#11]
Hi I get a lot of these lines when running the proxy. I'm sure it won't do any harm, but also don't think it's something to be happy with :-)

> 2016/02/23 23:30:23 Unsolicited response received on idle HTTP channel starting with "ns\":[\"0x4cf11c4f8e715c8ff066dbd8225fbf2db631b6c6350e5fa687c2c2a1afd04b3c\",\"0x2c92070b95f14cc88d5e303c49c389655ab604a4c1f65cd10b04650eb377b7e6\",\"0x5915470a9c1f3834343e3308e2d52ff26dd72a3bb117d36270b9854c13737a85\"],\"transactionsRoot\":\"0xb260c978718c17a2752a3054f3406ae31b3b6f8b83adaeb1d8019985e360d1a5\",\"uncles\":[]}}\n"; err=<nil>

**Comment by sammy007** [comment]
Proxy works great with stable geth, I didn't test it with development branch. Make sure your setup is ok. Give me more details how you are running geth and proxy. What golang version, what geth version, what OS.

**Comment by sammy007** [comment]
Ok, I reproduce this with golang 1.6 and geth from dev branch:

```
Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 200 OK\r\nContent-Length: 113\r\nContent-Type: application/json\r\n\r\n{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32600,\"message\":\"read tcp 127.0.0.1:8888-\\u003e127.0.0.1:60404: i/o timeout\"}}\n"; err=<nil>
```

**Comment by sammy007** [comment]
Well, reported to geth repo, it seems for now I can't do anything with it.

**Comment by jeeweevee** [comment]
Thanks, installed go1.4 and now I don't see errors anymore.

**Comment by sammy007** [comment]
I am tested it with 1.4 (develop) geth and it's ok now. Let me know if it works for you too or it's still issue.
