### ISSUE TITLE
JSON_RPC

### ISSUE THREAD

**Issue by jeeweevee** [sammy007/ether-proxy#12]
When I point GPU miners to the proxy I get (in the cmd of the miner):

> JSON-RPC problem. Probably couldn't connect. Retrying in 1...
miner  00:35:30|main  Getting work package...
  X  00:35:30|main  Failed to submit hashrate.
  X  00:35:30|main  Dynamic exception type: class jsonrpc::JsonRpcException
std::exception::what: Exception -32603 : INTERNAL_ERROR: : 404 page not found

**Comment by sammy007** [comment]
You are using wrong endpoint URL.

**Comment by jeeweevee** [comment]
What do you mean? You think my ethminer config is bad? Or something in the proxy config?

**Comment by jeeweevee** [comment]
This is my proxy config:

> {
        "threads": 2,

        "proxy": {
                "listen": "0.0.0.0:3333",
                "clientTimeout": "3m",
                "blockRefreshInterval": "100ms",
                "hashrateWindow": "15m",
                "submitHashrate": false,
                "luckWindow": "24h",
                "largeLuckWindow": "72h"
        },

        "frontend": {
                "listen": "0.0.0.0:80",
                "login": "admin",
                "password": ""
        },

        "upstreamCheckInterval": "5s",
        "upstream": [
                {
                        "name": "main",
                        "url": "http://127.0.0.1:9656",
                        "timeout": "10s"
                }
        ],

        "newrelicEnabled": false,
        "newrelicName": "MyEtherProxy",
        "newrelicKey": "SeCuRe_123",
        "newrelicVerbose": true
}

And my miner .bat:

> .\ethminer -G -F http://hereismyip:3333

**Comment by sammy007** [comment]
Must be like: http://hereismyip:3333/miner/40/rig-1
