### ISSUE TITLE
Hello, would you like to improve the ether-proxy for a complete ETH mine pool

### ISSUE THREAD

**Issue by coolsd** [sammy007/ether-proxy#14]
Hello, would you like to improve the ether-proxy for a complete ETH mine pool？
I want to pay 5BTC.
mail:coolsd@qq.com

**Comment by sammy007** [comment]
I have this project implemented already and this is my proposal for "An Open Source Mining Pool Bounty and DEVgrant". If Ethereum devs will approve it, I will publish it here on github.

**Comment by sammy007** [comment]
For now, you can look at testnet demo http://demo.eurohash.net/

**Comment by coolsd** [comment]
This is very good, your project or as always good, could you give me the test in advance?
Or I can purchase。thank you。

**Comment by sammy007** [comment]
Sorry, I can't give code/bins for now.

**Comment by coolsd** [comment]
OK，Looking forward to the project is launched, thank you for your efforts.

**Comment by sammy007** [comment]
For those who wanna try http://demo.eurohash.net/ pool - Don't mine there with GPU, only with CPU. Difficulty is very low, you will never see true GPU hashrate there in stats. Thanks.

**Comment by coolsd** [comment]
OK

**Comment by sammy007** [comment]
I am ready to sell my pool to you, let's talk about it on IRC freenode.net, PM me there or find me on #ethereum or #monero channel. Won't turn this issue tracker to a chat. Closing.
