### ISSUE TITLE
Stratum rigs

### ISSUE THREAD

**Issue by bcmob** [sammy007/ether-proxy#18]
Please add stratum protocol, if possible.

**Comment by sammy007** [comment]
Last donation received more than 3 months ago. Very unlikely, but who knows...

**Comment by d57heinz** [comment]
I can completely understand that.. Here is a little for your efforts.> Id also appreciate being able to connect claymores miner to this so i can go back solo.. If i could code it myself for the community i would.. Maybe this will help you or if you have a number we can work towards that will get this done.. Id appreciate it as i think the community would aswell.  Transaction submitted. TX ID: 0x90c01ef68f3793a87579f03c645c848178f919d53b55df0cc494508341918d0f

**Comment by sammy007** [comment]
If you are solo mining and want to mine with stratum, you can install https://github.com/sammy007/open-ethereum-pool and disable payouts on it. Stratum is compatible with eth-proxy and Claymore's closed source miner.

**Comment by sammy007** [comment]
https://github.com/sammy007/open-ethereum-pool is what I am busy with and very unlikely I will push some significant changes like stratum to proxy in several weeks.

**Comment by d57heinz** [comment]
Wow.  Very nice.. Thanks for that.  I will continue to support the projects.  Thanks so much.  Ill hit you up if i have any issues.. Best Regards Doug
