### ISSUE TITLE
Unexpected values reported in web interface

### ISSUE THREAD

**Issue by calfer** [sammy007/ether-proxy#19]
First, nice app!  As many have already stated, this provides the much needed ability to monitor rig health as well as node failover when solo mining.

An issue we are having is that we're seeing values in the Upstream Rejected column for a couple rigs and these are not totaled to be included under the Rejected heading at the top of the web interface just beneath Accepted.  Instead it shows a constant 0 while the value as reported under the Accepted heading at the top of the interface equals the sum of the reported values in the Accepted column for all rigs.  Are we misinterpreting your reporting?

Additionally, are the values in the Upstream Accepted column for each rig meant to be translated as 'mined blocks'?  In screenshots of previous ether-proxy releases I see the term 'Blocks' used in place of the current term 'Upstream'.  To be more clear, if I see an increase in value of 1 in the Upstream Accepted column (and in the Accepted heading at the top of the interface) is the intended message that I mined a new block that has been accepted onto the chain?

Lastly, as we're currently seeing a high Upstream Rejected percentage as compared to Upstream Accepted (4:5), what specific ether-proxy parameters and respective values do you recommend configuring in the config file so that we might see less Upstream Rejected occurrences?  We're currently using default values with two nodes and six (will be fifteen tonight) miners on the same subnet in a 1Gbps LAN with no perceived latency issues.

-calfer

**Comment by sammy007** [comment]
Upstream accepted = blocks accepted (in solo mode) and = shares accepted in pool mode. No idea about rejects.

**Comment by slavserver** [comment]
how to do that would be seen by the number of the extracted block? solo mode. where and how to improve the code? 
2. another question .. is it possible to make a separate page units Statistics? the example http://etc.digger.ws/#/blocks

3. ether proxy to connect to the node in the solo mode, you must include the option submithasherate> true?

**Comment by sammy007** [comment]
Use pool if you need pool-like stats. Closing as stale.
