### ISSUE TITLE
Order the entries in the "Miners" table

### ISSUE THREAD

**Issue by eupraxic** [sammy007/ether-proxy#2]
My miner IDs have the form "<hostname>-<gpu id>" (e.g. "miner1-4").  It would be convenient to be able to scan through the table to verify that all ethminers on a given host are performing as expected.  Currently, the entries are unordered.  If they were ordered by ID or IP, it would be easier to check the status of a mining server.

**Comment by sammy007** [comment]
Will do, it's planned.

**Comment by sammy007** [comment]
Added simple sorting by ID.

**Comment by eupraxic** [comment]
Looks good, thanks!
