### ISSUE TITLE
Ether-Proxy and MPOS

### ISSUE THREAD

**Issue by zimbo123** [sammy007/ether-proxy#20]
Hello,

i installed successfully the ether-proxy on my System. But now i want to configure it with the MPOS-System for the webinterface. I'm not sure about the config-file, in the global-inc.php of the MPOS i must configure the wallet and the algorithm.
What Kind of algorithm should i use? The documentation says following:

algorithm
•sha256d: Bitcoin and similar ones.
•scrypt: Litecoin and most of the all-coins.
•scryptn: Vertcoin and similar ones.
•x11: Darkcoin and similar ones

But for Ethereum??

Also i have a Problem with the rpc-wallet configuration. What port should i use? The web Port 8080, or the rpcport, that is in the geth.config? What username should i use, the wallet-adress or the username of the webinterface of ether-proxy?

Thanks for helping.

Best regards

Zimbo

**Comment by sammy007** [comment]
I don't know.
