### ISSUE TITLE
Add stratum?

### ISSUE THREAD

**Issue by mbush78** [sammy007/ether-proxy#25]
Do you plan on adding Stratum to this? If not, why - If so when? 
Thanks.

**Comment by sammy007** [comment]
I suggest to take a look on https://github.com/sammy007/open-ethereum-pool

**Comment by mbush78** [comment]
I've actually already been trying to run that and getting it going. 
So that has a proxy built into it already ? I did see reference to 'proxy' in the code but I didn't notice any way to ensure it was running or how to connect to it.  ... So when I tried to connect my node directly to stratum on 8008 if choked and spit out errors. And when I'm connected to 8888 the logs do not show that its sending anything to a 'stratum' connection. So I'm just a little confused. 

Thanks.

**Comment by sammy007** [comment]
Pool is derived from proxy. You can launch it like your own private pool, if you mine solo feel free to disable payouts there so your blocks will just rain to your coinbase/etherbase specified on geth.

**Comment by mbush78** [comment]
where are the payout settings you're talking about located ?

**Comment by sammy007** [comment]
If you wanna run open-ethereum-pool you should read documentation.

**Comment by mbush78** [comment]
I've read it, aside from your README is there more documentation I'm missing ?

**Comment by sammy007** [comment]
No because README is enough to run a pool.

**Comment by mbush78** [comment]
I humbly disagree.

**Comment by sammy007** [comment]
Me too.
