### ISSUE TITLE
Upstream not matching wallet

### ISSUE THREAD

**Issue by benkofk** [sammy007/ether-proxy#27]
Hello,

I use your ether-proxy, it's very good, but recently we have had two 'Last Submissions' not show up in our wallet. Is there a way to check which blocks are supposedly ours?

Thanks

**Comment by sammy007** [comment]
Last Submissions counter only indicate successful block submissions to a node, block can be uncle or orphan (because ethereum is not orphan-proof).

**Comment by benkofk** [comment]
Oh, I thought orphaned blocks were uncles and still paid. Is that not the case then?

**Comment by sammy007** [comment]
As I said block can be successful block, uncle (if some other miner wrapped it in his block) or orphan due to latency or geth/parity likely not in sync.

**Comment by benkofk** [comment]
Thanks

**Comment by sammy007** [comment]
You can check blocks and uncles on etherscan.io, etherchain can't show uncles.

**Comment by sammy007** [comment]
And if you caught 2 orphans in a row it's very likely something wrong with your geth. I highly suggest to switch to parity 1.3 https://github.com/ethcore/parity/wiki as faster implementation of ethereum node.
