### ISSUE TITLE
New ver

### ISSUE THREAD

**Issue by slavserver** [sammy007/ether-proxy#28]
the new version would like to see the following: 
1. Detailed mapping of statistics worker`s on a separate page (found time block, the sum of the found block, 5, 4.75 etc)
 2. on the main page, leave it at that.

**Comment by fluffypony** [comment]
@slavserver thank you for contacting @sammy007's coding services. We'd be glad to assist you with your request. Our base rates for client requested features are $75 an hour, payable in Bitcoin, Monero, or Ether.

For the work you have requested we estimate it will take about 23 hours of development, for a total of $1725. Would you like us to send an invoice to you via email, or just provide a payment address here?

**Comment by sammy007** [comment]
Hah hah, well, actually if you need detailed stats you must use https://github.com/sammy007/open-ethereum-pool
