### ISSUE TITLE
Miners don't show up in the table until they have reported their first share

### ISSUE THREAD

**Issue by eupraxic** [sammy007/ether-proxy#3]
It would be helpful to have a miner appear in the "Miners" table as soon as it first requests work.  In the case where I start a number of miners and one fails during startup, the table will show all miners are "green" and the failed miner will not be listed.

**Comment by sammy007** [comment]
This is by design, miners will never appear until they solved at least 1 share. After 1/2 of timeout it will be listed as yellow and then will be red.

**Comment by slavserver** [comment]
Извеняюсь за тикеты. Хочу доработать на отдельной странице список воркеров которые нарыли блок и время когда нарыл. Не могу найти команду в скрипте. Поможешь?

**Comment by sammy007** [comment]
Все данные в API на /stats по воркерам. Если надо пул - open-ethereum-pool. На винде он не работает. Что-то допиливать и консультировать нет времени, почему вы просто не можете майнить и все?

**Comment by slavserver** [comment]
Интузиазм хренов Наверно.  Спасибо
4 сент. 2016 г. 1:05 PM пользователь "Sammy Libre" <notifications@github.com>
написал:

**Comment by slavserver** [comment]
Сколько будет стоить передалать пул?

**Comment by sammy007** [comment]
Все вопросы в gitter или slack. Тут не чат.
