### ISSUE TITLE
Memory/CPU/HD requirements

### ISSUE THREAD

**Issue by daniel-lucio** [sammy007/ether-proxy#30]
Can you talk about memory requirements? As this is a proxy and no CPU math is done here, does a 512 MB RAM, 1 vCPU is enough?

**Comment by sammy007** [comment]
CPU is done here for share validation. Must be ok on this configuration, depends on hashrate. But you need to run a daemon like geth || parity so you need a multi core Xeon with 16+ GB RAM for it.

**Comment by daniel-lucio** [comment]
Ok, so to be clear. For a proxy a 512MB RAM, 1 vCPU is enough? (geth will be running in another machine) 
What about HD, does this proxy uses lot of space (comparing it with geth). Please elaborate.

**Comment by sammy007** [comment]
Should be ok. No space required.
