### ISSUE TITLE
static difficulty?

### ISSUE THREAD

**Issue by daniel-lucio** [sammy007/ether-proxy#32]
as I see, in the path /diff/id

why is difficulty static? As my understanding, difficulty is a value that constantly is increased, making it static will backfire if the miner doesn't updates its URL.

Please explain

**Comment by daniel-lucio** [comment]
(sorry, I am not a golang coder) I am reading the code, and I understand you internally update that value (file proxy/miner.go), the URL is just to have a number to start with, right?

**Comment by sammy007** [comment]
For http you can chose any diffficulty like 40-60-100. It's not static, you must set it on miner side.
