### ISSUE TITLE
can't go build -o ether-proxy main.go

### ISSUE THREAD

**Issue by jayraj9700** [sammy007/ether-proxy#34]
Followed all the steps but can't execute the - go build command, am shit at linux sorry, appreciate if anyone can help.

Installed GO 1.6  & already have parity instead of geth.
then did 
export GOPATH=$HOME/go 
and installed all the required packages, after that i key in the command "go build -o ether-proxy main.go"
it gives me an error no such file or directory found. 

What am i doing wrong here? and would this proxy work with ethcore parity instead of geth?

**Comment by sammy007** [comment]
U need to cd into directory with source:

```
git clone https://github.com/sammy007/ether-proxy.git
cd ether-proxy
go build -o ether-proxy main.go
```

**Comment by jayraj9700** [comment]
thax it worked just fine as the steps you provided
