### ISSUE TITLE
Proxy is working but could not connect my miners to it

### ISSUE THREAD

**Issue by jayraj9700** [sammy007/ether-proxy#35]
Hi Sammy,

Got the proxy working with parity node. It's green and blocks are syncing properly. But even after trying several setting i could not get my miners to work on proxy, seems like they are not getting connected and even not showing up on my proxy front-end.  

I use ethos distro on all my miners and am pointing them to "http://192.168.1.4:8546". Also if you can guide weather should i enable stratum proxy or keep it disabled on my ethos settings? Have attached my mining log with RPC errors.

![screenshot from 2016-12-31 16-51-29](https://cloud.githubusercontent.com/assets/23356246/21577230/aae1b622-cf79-11e6-8576-bad44c78c14f.png)
 
Here is my config.json file

`"threads": 2,

	"proxy": {
		"listen": "192.168.1.4:8546",
		"clientTimeout": "3m",
		"blockRefreshInterval": "100ms",
		"hashrateWindow": "15m",
		"submitHashrate": true,
		"luckWindow": "24h",
		"largeLuckWindow": "72h"
	},

	"frontend": {
		"listen": "0.0.0.0:8118",
		"login": "admin",
		"password": ""
	},

	"upstreamCheckInterval": "5s",
	"upstream": [
		{
			"pool": true,
			"name": "Crypto",
			"url": "http://192.168.1.4:8545",
			"timeout": "100s"
		}
	],

	"newrelicEnabled": false,
	"newrelicName": "MyEtherProxy",
	"newrelicKey": "SECRET_KEY",
	"newrelicVerbose": false
}`

**Comment by sammy007** [comment]
You must use `ethminer -F http://IP:PORT/miner/<diff>/<id>`.
