### ISSUE TITLE
CONNECTION

### ISSUE THREAD

**Issue by Nokomy** [sammy007/ether-proxy#36]
THE NEED TO ADDRESS SLOW CONNECTION MUST BE BROUGHT FORWARD,if we can participate from Nigeria, i assure there is a lot to gain from me and my team. AS some countries as it as standard access issue...internet service provider MTN's platform at this stage need to be able to access the UR money platform with the slow mode internet services they provide....and naturally they scheme us the client out to buy this services....i won't knowingly settle it.

**Comment by sammy007** [comment]
Sorry I have no bank account.
