### ISSUE TITLE
can't go get ethash

### ISSUE THREAD

**Issue by slabon** [sammy007/ether-proxy#37]
same as for open-ethereum-pool

package github.com/ethereum/go-ethereum/logger: cannot find package "github.com/ethereum/go-ethereum/logger" in any of:
        /usr/local/go/src/github.com/ethereum/go-ethereum/logger (from $GOROOT)
        /home/pool/go/src/github.com/ethereum/go-ethereum/logger (from $GOPATH)
package github.com/ethereum/go-ethereum/logger/glog: cannot find package "github.com/ethereum/go-ethereum/logger/glog" in any of:
        /usr/local/go/src/github.com/ethereum/go-ethereum/logger/glog (from $GOROOT)
        /home/pool/go/src/github.com/ethereum/go-ethereum/logger/glog (from $GOPATH)

**Comment by sammy007** [comment]
Ethash is not my problem. i already replied in previous ticket.

**Comment by slabon** [comment]
ok sure...

**Comment by sammy007** [comment]
Fixed. They broke it. Now works.
