### ISSUE TITLE
Cannot find package github.com/ethereum/go-ethereum/

### ISSUE THREAD

**Issue by andrewostroumov** [sammy007/ether-proxy#38]
Hello,

I have issue when fetch go dependencies. When i run go get github.com/ethereum/ethash I get:

```
package github.com/ethereum/go-ethereum/pow: cannot find package "github.com/ethereum/go-ethereum/pow" in any of:
	/usr/local/Cellar/go/1.8/libexec/src/github.com/ethereum/go-ethereum/pow (from $GOROOT)
	/Users/andrewostroumov/go/src/github.com/ethereum/go-ethereum/pow (from $GOPATH) 
```

Seems like go-ethereum v.1.5.9 has pow, but master - not. When I checkout v.1.5.9 this hasn't log, but master - has.

Any suggestions?

**Comment by douglashipocreme** [comment]
same here // ..

**Comment by sammy007** [comment]
Go spam this issue https://github.com/ethereum/ethash/issues/94 and this PR https://github.com/ethereum/ethash/pull/93

**Comment by karalabe** [comment]
This should be fixed with the current code.
