### ISSUE TITLE
Cant get working on mac OS

### ISSUE THREAD

**Issue by Ulysseus** [sammy007/ether-proxy#9]
I have installed the client when I type ./ether-proxy config.json I get Config error: invalid character 'â' looking for beginning of value
I have have searched the config file for that character its not there?
{
	"threads": 2,

	"proxy": {
		"listen": “10.0.0.105:8546",
		"clientTimeout": "3m",
		"blockRefreshInterval": "500ms",
		"hashrateWindow": "15m"
	},

	"frontend": {
		"listen": “10.0.0.105:8080"
    },

	"upstreamCheckInterval": "5s",
	"upstream": [
		{
			"name": "main",
			"url": "http://10.0.0.105:8545",
			"timeout": "10s"
		},
		{
			"name": "backup",
			"url": "http://10.0.0.105:8545",
			"timeout": "10s"
		}
	],

	"newrelicEnabled": false,
	"newrelicName": "MyEtherProxy",
	"newrelicKey": "SECRET_KEY",
	"newrelicVerbose": false
}

**Comment by sammy007** [comment]
Make config from config.example.json is a proper next editor.
